# Generated by Django 2.0.5 on 2018-07-28 13:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreenSite',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
