# Generated by Django 2.0.5 on 2018-07-30 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenox', '0002_wards'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenSiteWard',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=254)),
                ('wardname', models.CharField(max_length=70)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
